models:
  - name: dim_listings_cleansed
    description: "This table contains the Airbnb listings data."
    columns:
      - name: listing_id
        description: "The unique identifier for each listing."
        data_tests:
          - not_null
          - unique
      
      - name: host_id
        data_tests:
          -relationship
            arguments:
              to: ref('dim_host_cleansed')
              field: host_id
      
  - name: dim_hosts_cleansed
    columns:
    - name: host_id
      data_tests:
        -not_null
        -unique
    - name: is_superhost
      data_tests:
        - accepted_values:
            arguments:
              values: ['t', 'f']

